import { nativeSymbolOf, networkKey } from "@/lib/wallets/networkKey";
let fails = 0;
const eq = (name: string, got: string, want: string) => { const ok = got === want; if (!ok) fails++; console.log(`${ok ? "✅" : "❌"} ${name}: ${got}${ok ? "" : ` (esperado ${want})`}`); };
eq("Ethereum → eth", networkKey("Ethereum"), "eth");
eq("Ethereum (ETH) → eth", networkKey("Ethereum (ETH)"), "eth");
eq("eth → eth", networkKey("eth"), "eth");
eq("sem etiqueta → eth", networkKey(undefined), "eth");
eq("Arbitrum One → arbitrum", networkKey("Arbitrum One"), "arbitrum");
eq("Optimism (OP) → optimism", networkKey("Optimism (OP)"), "optimism");
eq("Base (Coinbase) → base", networkKey("Base (Coinbase)"), "base");
eq("Polygon (POL) → polygon", networkKey("Polygon (POL)"), "polygon");
eq("matic → polygon", networkKey("matic"), "polygon");
eq("BNB Smart Chain (BSC) → bsc", networkKey("BNB Smart Chain (BSC)"), "bsc");
eq("Avalanche C-Chain (AVAX) → avalanche", networkKey("Avalanche C-Chain (AVAX)"), "avalanche");
eq("zkSync Era → zksync", networkKey("zkSync Era"), "zksync");
eq("Linea → linea", networkKey("Linea"), "linea");
eq("Scroll → scroll", networkKey("Scroll"), "scroll");
eq("Mantle (MNT) → mantle", networkKey("Mantle (MNT)"), "mantle");
eq("desconhecida → minusculas", networkKey("Rede Nova"), "rede nova");
eq("nativo Fantom = FTM", nativeSymbolOf("Fantom (FTM)"), "FTM");
eq("nativo Mantle = MNT", nativeSymbolOf("Mantle (MNT)"), "MNT");
eq("nativo Scroll = ETH", nativeSymbolOf("Scroll"), "ETH");
eq("nativo Polygon = POL", nativeSymbolOf("Polygon (POL)"), "POL");
eq("nativo BSC = BNB", nativeSymbolOf("BNB Smart Chain (BSC)"), "BNB");
eq("nativo Avalanche = AVAX", nativeSymbolOf("Avalanche C-Chain (AVAX)"), "AVAX");
eq("nativo Arbitrum = ETH (L2 de Ethereum)", nativeSymbolOf("Arbitrum One"), "ETH");
eq("nativo Base = ETH", nativeSymbolOf("Base (Coinbase)"), "ETH");
eq("nativo Gnosis = XDAI", nativeSymbolOf("Gnosis Chain (xDAI)"), "XDAI");
eq("nativo Ethereum = ETH", nativeSymbolOf("Ethereum"), "ETH");
console.log(fails === 0 ? "\nTODOS OK" : `\n${fails} FALHA(S)`); process.exit(fails ? 1 : 0);
