import { computeFifo, parseTradesCsv, tradesToCsv, sanitizeTrade, type Trade } from "@/lib/portfolios/trades";
let fails = 0;
const eq = (name: string, got: number, want: number) => { const ok = Math.abs(got - want) < 1e-9; if (!ok) fails++; console.log(`${ok ? "✅" : "❌"} ${name}: ${got} ${ok ? "" : `(esperado ${want})`}`); };
const T = (o: Partial<Trade>): Trade => ({ id: Math.random().toString(36), type: "compra", asset: "BTC", assetName: "Bitcoin", quantity: 1, priceEur: 0, date: "2024-01-01", exchange: "", notes: "", ...o, totalEur: (o.quantity ?? 1) * (o.priceEur ?? 0) });
let r = computeFifo([T({ quantity: 2, priceEur: 100 }), T({ type: "venda", quantity: 2, priceEur: 150, date: "2024-06-01" })]);
eq("sem taxas → ganho (igual a antes)", r.realizedPnl, 100);
r = computeFifo([T({ quantity: 2, priceEur: 100, feeEur: 4 }), T({ type: "venda", quantity: 1, priceEur: 150, feeEur: 3, date: "2024-06-01" })]);
eq("venda parcial com taxas → ganho líquido 150-100-2-3", r.realizedPnl, 45);
eq("taxas imputadas ao lote", r.lots[0].fees, 5);
eq("custo em aberto inclui a taxa restante 1×(100+2)", r.byAsset.BTC.costOpen, 102);
eq("total de taxas", r.fees, 7);
eq("sanitize mantém feeEur", sanitizeTrade({ ...T({ quantity: 1, priceEur: 10 }), feeEur: 1.5, feeInput: 1.7 })!.feeEur ?? -1, 1.5);
eq("sanitize: taxa negativa é ignorada", sanitizeTrade({ ...T({ quantity: 1, priceEur: 10 }), feeEur: -2 })!.feeEur ?? 0, 0);
const orig = [T({ quantity: 0.5, priceEur: 60000, feeEur: 12.34, feeInput: 13.5, currency: "USD", priceInput: 65000 }), T({ type: "venda", quantity: 0.2, priceEur: 70000, date: "2025-02-01" })];
const back = parseTradesCsv(tradesToCsv(orig)).trades;
eq("CSV ida e volta: nº", back.length, 2);
eq("CSV ida e volta: feeEur", back[0].feeEur ?? -1, 12.34);
eq("CSV ida e volta: feeInput", back[0].feeInput ?? -1, 13.5);
eq("CSV ida e volta: sem taxa continua sem taxa", back[1].feeEur ?? 0, 0);
const o2 = parseTradesCsv("date,type,asset,quantity,price_eur,total_eur,exchange,notes,currency,price_original\n2024-01-01,buy,ETH,1,2000,2000,Kraken,,EUR,2000");
eq("CSV antigo (sem colunas de taxa) importa", o2.trades.length, 1);
eq("CSV antigo fica sem taxa", o2.trades[0].feeEur ?? 0, 0);
const o3 = parseTradesCsv("Date;Side;Symbol;Amount;Price;Gas Price;Fee\n01/03/2024;BUY;SOL;10;100;25;1,5");
eq("CSV de terceiros: lê 'Fee' e ignora 'Gas Price'", o3.trades[0]?.feeEur ?? -1, 1.5);
console.log(fails === 0 ? "\nTODOS OK" : `\n${fails} FALHA(S)`); process.exit(fails ? 1 : 0);
