// Cenário sintético para avaliar o Block sem base de dados: as mesmas secções
// que o browser e o servidor montam, com números conhecidos, para os testes
// (offline) e a avaliação ao vivo (com chaves de IA) verificarem respostas.

export const CENARIO_BLOCK = [
  "=== O QUE SEI DO UTILIZADOR (memória do Block; usa sem voltar a perguntar) ===",
  "País onde declara impostos: PT",
  "Idade: 40",
  "",
  "=== PORTEFÓLIO (conta \"GT 1\") — totais por categoria ===",
  "Valor total: € 886,78",
  "  - Carteiras on-chain (ETH/SOL/BTC/ADA): € 356,19",
  "  - DeFi: € 240,00",
  "  - Cripto adicionada manualmente: € 290,59",
  "",
  "=== CARTEIRAS ON-CHAIN (nomes/etiquetas, nunca endereços) ===",
  "Ethereum e redes EVM (1 carteira):",
  "  - Ledger (fria): 0,131402 ETH",
  "",
  "=== POSIÇÕES DEFI (abertas e fechadas, com pares) ===",
  "  - [carteira 1] Uniswap · rede base · liquidez · aberta · par ETH/USDC · $120,00 · taxa 0.05 % · no intervalo",
  "  - [carteira 1] Aave · rede arbitrum · emprestimo · aberta · $120,00 · depositado $300,00 · emprestado $150,00 · fator de saúde 1,80",
  "  - [carteira 1] Uniswap · rede base · liquidez · fechada · par ETH/USDT · $0,00",
  "",
  "=== CRIPTO REGISTADA MANUALMENTE (por carteira) ===",
  "  - BTC: Binance, 0,003 moedas, investido € 250,00, comprado em 12/03/2025",
  "",
  "=== PLANO FIRE (parâmetros guardados pelo utilizador) ===",
  "  - Despesas mensais: 2.000,00 EUR",
  "  - Investimento mensal: 500,00 EUR",
  "  - Retorno anual esperado: 7 %",
  "  - Múltiplo FIRE: 25× despesas anuais (regra dos 4,0 %)",
  "  - Número FIRE (despesas × 12 × múltiplo): 600.000 EUR",
  "",
  "=== HISTÓRICO DO PORTEFÓLIO (fotografias guardadas pela plataforma; valores em EUR da altura) ===",
  "Primeira fotografia: 07/07/2026 (€ 700,00). Fotografias usadas: 88.",
  "Valor de referência atual: € 886,78 (ao vivo).",
  "Variação por período (valor atual face ao valor na data base):",
  "  - 24 horas: +€ 6,78 (+0,8 %) face a € 880,00 em 04/10/2026",
  "  - 7 dias: +€ 16,78 (+1,9 %) face a € 870,00 em 28/09/2026",
  "  - 30 dias: +€ 36,78 (+4,3 %) face a € 850,00 em 05/09/2026",
  "  - 60 dias: +€ 66,78 (+8,1 %) face a € 820,00 em 06/08/2026",
  "  - 90 dias: +€ 86,78 (+10,8 %) face a € 800,00 em 07/07/2026",
  "  - 180 dias: sem fotografia suficientemente antiga (o histórico começa a 07/07/2026)",
  "  - 1 ano: sem fotografia suficientemente antiga (o histórico começa a 07/07/2026)",
  "  - desde a primeira fotografia: +€ 186,78 (+26,7 %) face a € 700,00 em 07/07/2026",
  "Máximo: € 900,00 em 20/08/2026 · Mínimo: € 700,00 em 07/07/2026.",
  "NOTAS: 1) As fotografias automáticas diárias repetem o último valor conhecido quando o utilizador não abre a página do Portefólio. 2) Se um período pedido não tem fotografia, explica desde quando há histórico e dá a variação do período mais próximo que exista. 3) NUNCA peças ao utilizador o valor antigo do portefólio nem inventes um. 4) Para percentagens, usa as já calculadas acima.",
  "",
  "=== PONTUAÇÃO DO PORTEFÓLIO (0–100, a mesma do ecrã) ===",
  "Pontuação: 72/100 (gravada em 05/10/2026).",
  "",
  "=== MERCADO AGORA (lido neste momento) ===",
  "Preços em USD e variação 24 h: BTC $112.345 (+1,2 %) · ETH $2.710 (−0,5 %) · SOL $185 (+2,3 %)",
  "Fear & Greed: 62/100 (Greed)",
].join("\n");

/** Perguntas com o que uma boa resposta tem de conter/evitar (regex sobre o texto limpo). */
export const PERGUNTAS_AVALIACAO: Array<{ id: string; pergunta: string; lang: "pt" | "en"; deve: RegExp[]; naoDeve: RegExp[]; seccoesEsperadas: string[] }> = [
  { id: "variacao-60d", pergunta: "Quanto subiu ou desceu o meu portefólio nos últimos 60 dias?", lang: "pt", deve: [/66,78|8,1\s?%/], naoDeve: [/indica-me|diz-me o valor|fornece|preciso que me d[êe]s|valor total do teu portef[óo]lio h[áa]/i, /\\\[|\\frac|\\text/], seccoesEsperadas: ["HISTÓRICO"] },
  { id: "defi", pergunta: "Que posições DeFi tenho abertas e com que pares?", lang: "pt", deve: [/Uniswap/, /ETH\/USDC/, /Aave/], naoDeve: [/n[ãa]o tenho (acesso|dados)/i], seccoesEsperadas: ["POSIÇÕES DEFI"] },
  { id: "fire", pergunta: "Qual é o meu número FIRE e quanto me falta?", lang: "pt", deve: [/600[.\s]?000/], naoDeve: [/\\\[|\\frac/], seccoesEsperadas: ["PLANO FIRE"] },
  { id: "en-30d", pergunta: "How much did my portfolio change over the last 30 days?", lang: "en", deve: [/36[.,]78|4[.,]3\s?%/], naoDeve: [/\bdias\b/], seccoesEsperadas: ["HISTÓRICO"] },
  { id: "mercado", pergunta: "Porque é que o meu portefólio mexeu hoje?", lang: "pt", deve: [/ETH|BTC|SOL/], naoDeve: [/\\\[|\\frac/], seccoesEsperadas: ["MERCADO AGORA"] },
];
